# Use postgres/example user/password credentials
version: '3'

services:

  #  medieval-fantasy-fights:
  #    image: quarkus/medieval-fantasy-fights-jvm:0.0.1
  #    restart: always
  #    ports:
  #      - "5005:5005"
  #      - "8082:8082"
  #    depends_on:
  #      - "mongo"
  #    environment:
  #      JAVA_ENABLE_DEBUG: "true"
  #    networks:
  #      - internal
  #      - db

  mongo:
    image: mongo:5.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: mff
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo-init-scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/mongo:/data/db
    networks:
      - db

  #  proxy:
  #    image: nginx:1.21-alpine
  #    ports:
  #      - "8083:80"
  #    volumes:
  #      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #    networks:
  #      - internal

  postgres:
    image: postgres:14.2-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    command: -c ssl=off
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    #      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak

  keycloak:
    image: local/keycloak:17.0.0
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - internal

  mailserver:
    image: rnwood/smtp4dev
    ports:
      - "3001:80"
      - "2525:25"
    restart: unless-stopped
    networks:
      - internal

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - "postgres"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - internal


networks:
  db:
    external: false
  internal:
    external: false