# Configuration file
quarkus:
  application:
    name: midgard-arena
    version: 0.0.1
  http:
    port: 8082
  live-reload:
    watched-resources:
      - META-INF/resources/build/bundle.js
      - META-INF/resources/build/bundle.js.map
      - META-INF/resources/global.css
      - META-INF/resources/index.html
  log:
    file:
      enable: true
      path: src/test.log
  mongodb:
    connection-string: "mongodb://localhost:27017"
    database: midgard
    credentials:
      username: admin
      password: admin
